version: '3.8'

services:
  db:
    image: postgres:14
    container_name: db_api_pedidos
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_api_pedidos
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - log_volume:/app/logs
    command: ["sh", "/app/entrypoint.sh"]

volumes:
  postgres_data:
  static_volume:
  log_volume:
